language: node_js
node_js:
  - 'stable'
os:
  - linux
  - osx

before_script:
  - npm install
  - npm run build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    fi

script:
  - npm run lint
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

