version: "{build}"

environment:
  - nodejs_version: "7"

init:
  - git config --global core.autocrlf false

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

build: off
deploy: off

branches:
  only:
    - master
